# CMake generated Testfile for 
# Source directory: /home/jpollak/src/jbcpollak/Calico
# Build directory: /home/jpollak/src/jbcpollak/Calico
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TypeDefsTest "typedefs_test")
set_tests_properties(TypeDefsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;282;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(GeometryTest "geometry_test")
set_tests_properties(GeometryTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;295;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(BSplineTest "bspline_test")
set_tests_properties(BSplineTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;309;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(TrajectoryTest "trajectory_test")
set_tests_properties(TrajectoryTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;321;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(WorldModelTest "world_model_test")
set_tests_properties(WorldModelTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;333;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(GyroscopeModelsTest "gyroscope_models_test")
set_tests_properties(GyroscopeModelsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;345;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(GyroscopeCostFunctorTest "gyroscope_cost_functor_test")
set_tests_properties(GyroscopeCostFunctorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;357;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(GyroscopeLibTest "gyroscope_test")
set_tests_properties(GyroscopeLibTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;369;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(AccelerometerModelsTest "accelerometer_models_test")
set_tests_properties(AccelerometerModelsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;381;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(AccelerometerCostFunctorTest "accelerometer_cost_functor_test")
set_tests_properties(AccelerometerCostFunctorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;393;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(AccelerometerLibTest "accelerometer_test")
set_tests_properties(AccelerometerLibTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;405;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(CameraModelsTest "camera_models_test")
set_tests_properties(CameraModelsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;417;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(CameraCostFunctorTest "camera_cost_functor_test")
set_tests_properties(CameraCostFunctorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;429;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(CameraLibTest "camera_test")
set_tests_properties(CameraLibTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;441;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(BatchOptimizerTest "batch_optimizer_test")
set_tests_properties(BatchOptimizerTest PROPERTIES  _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;455;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(python_bindings_test "python3" "-m" "pytest" "/home/jpollak/src/jbcpollak/Calico/calico/test/python_bindings_test.py")
set_tests_properties(python_bindings_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/jpollak/src/jbcpollak/Calico:" WORKING_DIRECTORY "/home/jpollak/src/jbcpollak/Calico/calico/test" _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;457;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
add_test(python_utils_test "python3" "-m" "pytest" "/home/jpollak/src/jbcpollak/Calico/calico/test/python_utils_test.py")
set_tests_properties(python_utils_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/jpollak/src/jbcpollak/Calico:" WORKING_DIRECTORY "/home/jpollak/src/jbcpollak/Calico/calico/test" _BACKTRACE_TRIPLES "/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;463;add_test;/home/jpollak/src/jbcpollak/Calico/CMakeLists.txt;0;")
